name: PR Quality Gate

on:
  pull_request:
    branches:
      - main

# Cancel previous runs on same PR when a new push is made
concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  qa:
    name: Quality Gate
    uses: ./.github/workflows/qa.yml
    with:
      save-coverage: false
